### ISSUE TITLE
Difficulty port mapping for apps

### ISSUE THREAD

**Issue by tmwclaxton** [dockur/umbrel#11]
Hey!  Thank you for making this repo, it's exactly what I need!

I am having one issue, so if you download the Bitcoin Node app it requires localhost:2100 ; however, if I port map 2100:2100 in docker-compose the app can't boot with this error

> umbrel           | Error response from daemon: driver failed programming external connectivity on endpoint bitcoin_app_proxy_1 (20b64ffe404142b9ca8a6471d7fafb3bdba53a377d154a2939feef3280b33be8): Bind for 0.0.0.0:2100 failed: port is already allocated

If I do 2101:2100 the app will boot, but I cannot access it through the host network at localhost:2101

i.e.
```
umbrel:
        image: dockurr/umbrel
        container_name: umbrel
        ports:
            - 81:80
            - 2100:2100
            - 12596:12596
        volumes:
            - "sail-umbrel:/data"
            - "/var/run/docker.sock:/var/run/docker.sock"
        stop_grace_period: 1m
```
